spring:
  application:
    name: @project.artifactId@
  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost:27017/mydatabase}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:secret}
