name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        ./mvnw spring-boot:build-image \
          -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: |
          ghcr.io/${{ github.repository }}

    - name: Build and push Docker images
      run: |
        docker images ls
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        
        echo ${{ steps.meta.outputs.tags }}
        echo  ${{ steps.meta.outputs.labels }}
