name: Build
run-name: Build Pipeline
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'oas/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: 
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: versioning
      id: versioning
      run: |
          VERSION=$(date +"%d%m%Y%H%M")
          echo ::set-output name=version::$VERSION

    - name: Build with Maven
      run: |
        ./mvnw spring-boot:build-image \
          -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:${{ steps.versioning.outputs.version }}

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker image ls
        docker push ghcr.io/${{ github.repository }}:${{ steps.versioning.outputs.version }}
