name: OAS deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  github-pages-deployment:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      packages: write
      id-token: write
      pages: write
    steps:
      - name: Checkout 
      - name: Configure Pages
        uses: actions/configure-pages@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: oas
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    
